version: "3.7"
services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:docker@db:5432/fit-db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fit

  db:
    image: postgres:latest
    ports:
      - "5435:5432"
    command: postgres -c max_connections=200
    user: postgres
    environment:
      - POSTGRES_DB=fit-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fit-db"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - fit

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - user_microservice
      - coach_microservice
    networks:
      - fit

  user_microservice:
    build: ./src/user_microservice
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://postgres:docker@db:5432/fit-db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fit

  coach_microservice:
    build: ./src/coach_microservice
    ports:
      - "5003:5003"
    environment:
      - JWT_SECRET_KEY=your-secret-key
    depends_on:
      - user_microservice
    networks:
      - fit

networks:
  fit:
